ci: remove -m because
Run coverage -m run pytest . --pyargs
no such option: -m
Full documentation is at https://coverage.readthedocs.io
Use 'coverage help' for help.
Error: Process completed with exit code 1.